### ISSUE TITLE
Normcore avatar head is not tracking

### ISSUE THREAD

**Issue by josh1hart** [NormalVR/Normcore-Documentation#12]
I am using an XROrigin with all aspects working work as expected even with the normcore hands tracking to the XR controllers. Sadly the normcore head is not tracking with the main camera.

**Comment by maxweisel** [comment]
This isn't a bug in Normcore. By default RealtimeAvatarManager will try to get the head position via the XRNode API, but in AR Unity doesn't supply it, they only supply the camera position, but the head position returns 0,0,0 when queried. All of that said, you can correct this by wiring whatever transform you want into RealtimeAvatarManager's head input in the scene.
