### ISSUE TITLE
Stopwatch example not working

### ISSUE THREAD

**Issue by kantagara** [NormalVR/Normcore-Documentation#9]
Hey all, I've tried to follow the example but it seems that Stopwatch Monobehavior doesn't accept StopwatchModel https://prnt.sc/1wnmpdt I did make StopWatchModel extend the actual RealTimeModel https://prnt.sc/1wnn48h but that didn't get me much further. So if you guys could point me out on what I'm doing wrong I would gladly appreciate that. Thanks!

**Comment by maxweisel** [comment]
Please ask on the forum or on discord. We don't offer support on github issues.
